### ISSUE TITLE
CWB binaries not in PATH

### ISSUE THREAD

**Issue by SpitfireX** [mocdaniel/docker-cqpweb#1]
In the container the CWB binary location is not part of the default PATH and thus the CWB is not easily accessible from the shell. Because of that tools like cqp and cwb-encode need to be called from their explicit binary location in `/usr/local/cwb-3.4.19/bin/`.

Proposed solution: add `/usr/local/cwb-3.4.19/bin/` to the default PATH for the container or build the CWB with the `SITE=standard` option.

**Comment by mocdaniel** [comment]
Thanks for reporting this issue. I simply forgot to do the necessary configuration since my main goal was to provide a running cqpweb instance. Will get fixed with the next hotfix.
