### ISSUE TITLE
CQPweb security error on file upload

### ISSUE THREAD

**Issue by SpitfireX** [mocdaniel/docker-cqpweb#2]
CQPweb returns a security error (see attached log) when trying to upload files on the same computer the docker container is running on. This only happens when uploading from the docker host.

Steps to reproduce:
- start an instance of the container
- open a web browser on the same computer and go to Admin Control Panel -> View upload area (`/adm/index.php?ui=uploadArea`)
- try uploading an arbitrary file 

[upload_error.log](https://github.com/mocdaniel/docker-cqpweb/files/4282945/upload_error.log)

**Comment by mocdaniel** [comment]
Thanks for reporting this, I will look into this asap.

**Comment by mocdaniel** [comment]
I could not reproduce the behaviour you described. Due to the php-implementation of the uploading process, CQPweb might have problems with certain oddities such as file names, content, endings etc. Could you provide the exact file you tried to upload?

**Comment by mocdaniel** [comment]
Issue closed as there was no actual problem or bug but wrong individual configuration.
