### ISSUE TITLE
MySQL in different container?

### ISSUE THREAD

**Issue by perrotuerto** [mocdaniel/docker-cqpweb#6]
Hi, thanks for this container, we are using it in our organization. I just want to ask you if there is an specific reason the MySQL is not setup in a different container.

**Comment by mocdaniel** [comment]
Hey, 

no problem, I'm glad you find it useful. While I am well aware that putting multiple services into a single container is a strong anti-pattern, the intention behind this decision is to provide non-tech-savvy users a single container image for the easiest possible usage. This way, they won't have to manage multiple containers e.g. via Docker Compose.

However, feel free to fork this project and run MySQL in a separate container.

I hope this answers your question?

**Comment by perrotuerto** [comment]
Oh, no worries I completely understand the situation. I will proceed as you say. Thanks!
